# Generated by Django 3.0.3 on 2021-06-12 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('duration', models.PositiveIntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('long_name', models.CharField(max_length=127)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activated', models.BooleanField(default=False)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('is_organization', models.BooleanField(default=False)),
                ('seconds_left', models.BigIntegerField(default=0)),
                ('plan_subscribed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='project.Plans')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='User Subscription')),
            ],
        ),
    ]
