# Generated by Django 3.0.3 on 2021-06-12 17:00

from django.db import migrations


class Migration(migrations.Migration):
    
    def create_plans(apps, schema_editor):

        Plans = apps.get_model('project', 'Plans')
        db_alias = schema_editor.connection.alias

        Plans.objects.using(db_alias).bulk_create([
        Plans(name='monthly_org', long_name="Organization Monthly", price=5000.00, duration =30),
        Plans(name='monthly_ind', long_name="Individual Monthly", price=2000.00, duration =30),
    ])

    dependencies = [
        ('project', '0002_plans_subscription'),
    ]

    operations = [
        migrations.RunPython(create_plans, migrations.RunPython.noop)
    ]

