# Generated by Django 3.0.3 on 2021-06-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_populate_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_installment_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
